In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
titanic = pd.read_csv('/content/drive/MyDrive/30_days_of_Code/titanic_cleaned.csv')

In [ ]:
import pandas as pd

titanic_feature = pd.read_csv('/content/drive/MyDrive/30_days_of_Code/titanic_feature.csv')

# Display the first 5 rows of the DataFrame
print(titanic_feature.head(3))

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0

   Parch            Ticket     Fare    Cabin Embarked  Family Size  IsAlone  \
0      0         A/5 21171   7.2500  B96 B98        S            2        0
1      0          PC 17599  71.2833      C85        C            2        0
2      0  STON/O2. 3101282   7.9250  B96 B98        S            1        1

   IsChild Title Age_Range
0        0    Mr     Youth
1        0   Mrs    Adults
2        0  Miss     Youth

In [ ]:
titanic_feature['Age_Range'].value_counts()

Age_Range
Youth        510
Adults       217
Teenagers     95
Children      69
Name: count, dtype: int64

In [ ]:
sex_dummies = pd.get_dummies(
    titanic_feature['Sex'],
    prefix='Sex',
    dtype=int
)

In [ ]:
titanic_feature = pd.concat(
    [titanic_feature, sex_dummies],
    axis=1
)
titanic_feature.drop(columns=['Sex'], inplace=True)
titanic_feature.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Family Size', 'IsAlone',
       'IsChild', 'Title', 'Age_Children', 'Age_Teenagers', 'Age_Youth',
       'Age_Adults', 'Sex_female', 'Sex_male', 'Sex_female', 'Sex_male',
       'Sex_female', 'Sex_male'],
      dtype='object')

In [ ]:
titanic_feature = titanic_feature.loc[:, ~titanic_feature.columns.duplicated()]
titanic_feature.columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Family Size',
       'IsAlone', 'IsChild', 'Age_Children', 'Age_Teenagers', 'Age_Youth',
       'Age_Adults', 'Sex_female', 'Sex_male', 'Age_Range', 'Embarked_C',
       'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [ ]:
titanic_feature["Age"].value_counts().sum()

bins = [0, 12, 19, 35, 100]
categories = ["Children", "Teenagers", "Youth", "Adults"]

titanic_feature["Age_Range"] = pd.cut(titanic_feature["Age"], bins=bins, labels=categories, right=True)

In [ ]:
titanic_feature = titanic_feature.loc[
    :, ~titanic_feature.columns.str.startswith('Age_')
]

In [ ]:
titanic_feature.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Family Size', 'IsAlone',
       'IsChild', 'Title', 'Age_Children', 'Age_Teenagers', 'Age_Youth',
       'Age_Adults', 'Sex_female', 'Sex_male', 'Age_Range'],
      dtype='object')

In [ ]:
age_dummies = pd.get_dummies(
    titanic_feature['Age_Range'],
    prefix='Age',
    dtype=int
)

titanic_feature = pd.concat(
    [titanic_feature, age_dummies],
    axis=1
)

In [ ]:
titanic_feature.drop(columns=['Age_Range'], inplace=True)

In [ ]:
titanic_feature["Embarked"] = titanic["Embarked"]

In [ ]:
embarked_dummies = pd.get_dummies(titanic_feature["Embarked"], prefix="Embarked", dtype=int)
titanic_feature = pd.concat([titanic_feature, embarked_dummies], axis=1)
titanic_feature.drop(columns=["Embarked"], inplace=True)
titanic_feature.columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Family Size',
       'IsAlone', 'IsChild', 'Age_Children', 'Age_Teenagers', 'Age_Youth',
       'Age_Adults', 'Sex_female', 'Sex_male', 'Age_Range', 'Embarked_C',
       'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [ ]:
def drop_unneeded_columns(df):
    """
    Drop unnecessary columns from the Titanic dataset.
    """
    cols_to_drop = ['PassengerId', 'Name', 'Ticket', 'Cabin', 'Title','Age_Range']
    return df.drop(columns=[col for col in cols_to_drop if col in df.columns])

titanic_feature = drop_unneeded_columns(titanic_feature)
titanic_feature.columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Family Size',
       'IsAlone', 'IsChild', 'Age_Children', 'Age_Teenagers', 'Age_Youth',
       'Age_Adults', 'Sex_female', 'Sex_male', 'Embarked_C', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')

In [ ]:
features = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Family Size',
       'IsAlone', 'IsChild', 'Age_Children', 'Age_Teenagers', 'Age_Youth',
       'Age_Adults', 'Sex_female', 'Sex_male', 'Embarked_C',
       'Embarked_Q', 'Embarked_S']

target = 'Survived'

print("=== Features used for modeling: === ")
print(features)
print("\n=== Target variable: === ")
print(target)

=== Features used for modeling: ===
['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Family Size', 'IsAlone', 'IsChild', 'Age_Children', 'Age_Teenagers', 'Age_Youth', 'Age_Adults', 'Sex_female', 'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S']

=== Target variable: ===
Survived

In [ ]:
titanic_feature.head(3)

,Survived,Pclass,Age,SibSp,Parch,Fare,Family Size,IsAlone,IsChild,Age_Children,Age_Teenagers,Age_Youth,Age_Adults,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,2,0,0,0,0,1,0,0,1,0,0,1
1,1,1,38.0,1,0,71.2833,2,0,0,0,0,0,1,1,0,1,0,0
2,1,3,26.0,0,0,7.9250,1,1,0,0,0,1,0,1,0,0,0,1

In [ ]:
for col in features:
    print(f"\nSurvival rate by {col}")
    print(titanic_feature.groupby(col)['Survived'].mean())

Survival rate by Pclass
Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

Survival rate by Age
Age
0.42     1.0
0.67     1.0
0.75     1.0
0.83     1.0
0.92     1.0
        ...
70.00    0.0
70.50    0.0
71.00    0.0
74.00    0.0
80.00    1.0
Name: Survived, Length: 89, dtype: float64

Survival rate by SibSp
SibSp
0    0.345395
1    0.535885
2    0.464286
3    0.250000
4    0.166667
5    0.000000
8    0.000000
Name: Survived, dtype: float64

Survival rate by Parch
Parch
0    0.343658
1    0.550847
2    0.500000
3    0.600000
4    0.000000
5    0.200000
6    0.000000
Name: Survived, dtype: float64

Survival rate by Fare
Fare
0.0000      0.066667
4.0125      0.000000
5.0000      0.000000
6.2375      0.000000
6.4375      0.000000
              ...
227.5250    0.750000
247.5208    0.500000
262.3750    1.000000
263.0000    0.500000
512.3292    1.000000
Name: Survived, Length: 248, dtype: float64

Survival rate by Family Size
Family Size
1     0.303538
2     0.552795
3     0.578431
4     0.724138
5     0.200000
6     0.136364
7     0.333333
8     0.000000
11    0.000000
Name: Survived, dtype: float64

Survival rate by IsAlone
IsAlone
0    0.505650
1    0.303538
Name: Survived, dtype: float64

Survival rate by IsChild
IsChild
0    0.361702
1    0.503597
Name: Survived, dtype: float64

Survival rate by Age_Children
Age_Children
0    0.367397
1    0.579710
Name: Survived, dtype: float64

Survival rate by Age_Teenagers
Age_Teenagers
0    0.380653
1    0.410526
Name: Survived, dtype: float64

Survival rate by Age_Youth
Age_Youth
0    0.425197
1    0.352941
Name: Survived, dtype: float64

Survival rate by Age_Adults
Age_Adults
0    0.384273
1    0.382488
Name: Survived, dtype: float64

Survival rate by Sex_female
Sex_female
0    0.188908
1    0.742038
Name: Survived, dtype: float64

Survival rate by Sex_male
Sex_male
0    0.742038
1    0.188908
Name: Survived, dtype: float64

Survival rate by Embarked_C
Embarked_C
0    0.344398
1    0.553571
Name: Survived, dtype: float64

Survival rate by Embarked_Q
Embarked_Q
0    0.383292
1    0.389610
Name: Survived, dtype: float64

Survival rate by Embarked_S
Embarked_S
0    0.502041
1    0.339009
Name: Survived, dtype: float64

In [ ]:
titanic_feature.columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Family Size',
       'IsAlone', 'IsChild', 'Age_Children', 'Age_Teenagers', 'Age_Youth',
       'Age_Adults', 'Sex_female', 'Sex_male', 'Embarked_C', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')